/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_loki_lokinet_LokinetVPN_VPNInfo */

#ifndef _Included_network_loki_lokinet_LokinetVPN_VPNInfo
#define _Included_network_loki_lokinet_LokinetVPN_VPNInfo
#ifdef __cplusplus
extern "C"
{
#endif
#ifdef __cplusplus
}
#endif
#endif
