/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class network_loki_lokinet_LokinetConfig */

#ifndef _Included_network_loki_lokinet_LokinetConfig
#define _Included_network_loki_lokinet_LokinetConfig
#ifdef __cplusplus
extern "C"
{
#endif
    /*
     * Class:     network_loki_lokinet_LokinetConfig
     * Method:    Obtain
     * Signature: (Ljava/lang/String;)Ljava/nio/ByteBuffer;
     */
    JNIEXPORT jobject JNICALL Java_network_loki_lokinet_LokinetConfig_Obtain(JNIEnv*, jclass, jstring);

    /*
     * Class:     network_loki_lokinet_LokinetConfig
     * Method:    Free
     * Signature: (Ljava/nio/ByteBuffer;)V
     */
    JNIEXPORT void JNICALL Java_network_loki_lokinet_LokinetConfig_Free(JNIEnv*, jclass, jobject);

    /*
     * Class:     network_loki_lokinet_LokinetConfig
     * Method:    Load
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_lokinet_LokinetConfig_Load(JNIEnv*, jobject);

    /*
     * Class:     network_loki_lokinet_LokinetConfig
     * Method:    Save
     * Signature: ()Z
     */
    JNIEXPORT jboolean JNICALL Java_network_loki_lokinet_LokinetConfig_Save(JNIEnv*, jobject);

    /*
     * Class:     network_loki_lokinet_LokinetConfig
     * Method:    AddDefaultValue
     * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
     */
    JNIEXPORT void JNICALL
    Java_network_loki_lokinet_LokinetConfig_AddDefaultValue(JNIEnv*, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
