#!/usr/bin/env bash
# this shell script will be replaced by a proper program in the future (probably)
#

if [ -z "$1" ]
then
  url="https://i2p.rocks/i2procks.signed"
else
  url="$1"
fi

echo "downloading $url"

if [ ! -d "$HOME/.lokinet" ]
then
  mkdir $HOME/.lokinet
fi

wget -O $HOME/.lokinet/bootstrap.signed "$url" || echo "failed to download bootstrap from $url"
