#!/usr/bin/env bash
# this shell script will be replaced by a proper program in the future (probably)
#
# from https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

if [ -z "$1" ]
then
  url="https://i2p.rocks/i2procks.signed"
else
  url="$1"
fi

echo "downloading $url"

if [ ! -d "$HOME/.lokinet" ]
then
  mkdir $HOME/.lokinet
fi

# use temp file to not overrwrite existing bootstrap file on fail
tmp=mktemp

# MacOS does not have wget without homebrew but does have curl
# Rick also had indicated most BSDs have curl too
curl "$url" > "$tmp" && \
    (mv "$tmp" "$HOME/.lokinet/bootstrap.signed" && echo -e "${GREEN}lokinet successfully bootstrapped${NC}" ) \
        || echo -e "${RED}failed to download bootstrap from $url${NC}"
rm -f "$tmp"
