[DEFAULT]
upstream-branch = master
debian-branch = ubuntu/resolute
upstream-tag = v%(version)s

[buildpackage]
submodules = true
ignore-new = true
pbuilder = true
dist = resolute


[pq]
ignore-new = true
