.TH "loki-service-nodes" "7" "Dec 3, 2018"

.SH "NAME"
loki-service-nodes \- a note on lokinet's crypto-economics
.SH "The Quick Rundown"

.PP
Loki's service nodes are a blockchain based PKI management infrastructure used as a psuedo directory authority for lokinet routers.
While using the network as a client costs absolutely nothing,
in order to run machines participating in routing one must stake loki tokens,
locking tokens for a period of time.
During this time the router with the identity key provided in the staking transaction on the loki blockchain will commit to participation for the duration the tokens are locked for.

.PP
Periodically the network performs self-tests on service nodes to ensure service nodes are functional and well behaved.
Functional and well behaved service nodes get a block reward for providing routing of traffic.
In the event of many test failures the network dergesisters the service node,
effectively kicking it from the network as a participating router.

.PP
In conclusion,
it is conjectured that the net effect is that well behaved reliable routing infrastucture is incentivesed economically.
