.TH "lokinet-bootstrap" "1" "Dec 03, 2018"

.SH "NAME"
lokinet-bootstrap \- lokinet network bootstrap utilitiy
.SH "SYNOPSIS"
.B lokinet-bootstrap
[\fI nodeinfo-url ]
.SH "DESCRIPTION"

.PP
This script bootstraps lokinet into the main network by downloading a trusted signed router contact.

.SH "OPTIONS"

.IP \fBnodeinfo-url\fR
use an alternative url for bootstrap.

.RE

.SH "SEE ALSO"

lokinet configuration. \fBlokinet(1)\fR

.SH "AUTHOR"
This manual page was written by Jeff <\m[blue]\fBjeff@i2p\&.rocks\fR\m[]>
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the same license of lokinet source code.
.RE
See the LICENSE file for more information.

