.TH "lokinet" "1" "Oct 28, 2018"

.SH "NAME"
lokinet \- Reference implementation for LLARP.
.SH "SYNOPSIS"
.B lokinet
[\fI options ... \fR] [\fI config.ini \fR]
.SH "DESCRIPTION"

.PP
For a number of years, work has been proceeding in order to bring prefection
to the crudely concieved idea of a packet based onion routing protocol with a 
cryptoeconomical sybil resistence incentive that not only would be able to
provide low latency anonymous internet access but also be capable of 
automatically tunneling all local network traffic over said mixnet. Such an a
program would be the turbo encabu...\fBlokinet\fR . Now basically the only new
principle involved is that now instead of restricting the user to using TCP and 
exposing a socks proxy or transparent proxy like Tor, an ip tunnel is provided
with a dns resolver for intercepting lookups for the .loki tld. The original
implementation was in C but eventually devolved into C++ in such a way that 
there is a public C api but internally entirely implemented with C++11 wrapped
with a foriegn function interface. The latter being more rapidly developable,
but I digress ...

.SH "OPTIONS"

.IP \fB-g\fR
Generate config file
.IP \fB-f\fR
Force overwrite of existing config file
.IP \fB-r\fR
Configure to be a relay

.RE

.SH "FILES"

.I $HOME/.lokinet/

.IP
The default runtime directory

.RE

.I $HOME/.lokinet/lokinet.ini

.IP
The default config file.

.RE
.SH "SEE ALSO"
Documentation for lokinet configuration with loki service nodes.
.SH "AUTHOR"
This manual page was written by Jeff <\m[blue]\fBjeff@i2p\&.rocks\fR\m[]>
.PP
Permission is granted to copy, distribute and/or modify this document under the terms of the same license of lokinet source code.
.RE
See the LICENSE file for more information.
