#!/bin/sh
setcap cap_net_admin,cap_net_bind_service=+eip /usr/bin/lokinet || echo "failed to setcap lokinet"
adduser --quiet --system --home /var/lib/lokinet debian-lokinet || echo "debian-lokinet user not added"
exit 0
