function(add_log_tag target)
  get_target_property(TARGET_SRCS ${target} SOURCES)
  foreach(F ${TARGET_SRCS})
    get_filename_component(fpath "${F}" ABSOLUTE)
    string(REPLACE "${PROJECT_SOURCE_DIR}/" "" logtag "${fpath}")
    set_property(SOURCE ${F} APPEND PROPERTY COMPILE_DEFINITIONS LOG_TAG=\"${logtag}\")
  endforeach()
endfunction()
