#ifndef LLARP_PROTO_HPP
#define LLARP_PROTO_HPP

#ifndef LLARP_PROTO_VERSION
#define LLARP_PROTO_VERSION (0)
#endif

#ifndef LLARP_ETH_PROTO
#define LLARP_ETH_PROTO (0xD1CE)
#endif

#ifndef LLARP_KEYFILE_VERSION
#define LLARP_KEYFILE_VERSION (1)
#endif

#endif
